services:
  nginx:
    image: nginx:1.21
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/html:ro
      - ./assets:/assets:ro
      - ./.well-known:/.well-known:ro

  sass:
    build: .
    image: builder
    volumes:
      - ".:/app"
    command: sass --watch -s compressed assets/sass:assets/dist/css
    stop_signal: SIGKILL

  babel:
    build: .
    image: builder
    volumes:
      - ".:/app"
    command: babel --verbose --watch js -d assets/dist/js
    stop_signal: SIGKILL
