services:
  nginx:
    image: nginx:1.21
    networks:
      spittle:
        aliases:
          - kvikshaug
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/html:ro
      - ./assets:/assets:ro

  sass:
    build: .
    image: builder
    volumes:
      - ".:/app"
    command: sass -s compressed assets/sass:assets/dist/css

  babel:
    build: .
    image: builder
    volumes:
      - ".:/app"
    command: babel --verbose js -d assets/dist/js

networks:
  spittle:
    external: true
