services:
  nginx:
    image: nginx:1.21
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets:/assets:ro
      - ./.well-known:/.well-known:ro

  web:
    build: .
    image: kvikshaug.no
    networks:
      default:
        aliases:
          - kvikshaug
    volumes:
      - ".:/app"
    environment:
      - ENVIRONMENT=development
      - FLASK_SKIP_DOTENV=1
    command: gunicorn -c gunicorn.py kvikshaug.wsgi:app

  sass:
    image: kvikshaug.no
    volumes:
      - ".:/app"
    command: sass --watch -s compressed assets/sass:assets/css
    stop_signal: SIGKILL

  babel:
    image: kvikshaug.no
    volumes:
      - ".:/app"
    command: babel --verbose --watch js -d assets/js
    stop_signal: SIGKILL
