services:
  nginx:
    image: nginx:1.21
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./assets:/assets:ro"
      - "./.well-known:/.well-known:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.kvikshaug-static.loadBalancer.server.port=80"
      - "traefik.http.routers.kvikshaug-static.rule=Host(`kvikshaug.no`) && (PathPrefix(`/assets`) || PathPrefix(`/.well-known`))"
      - "traefik.http.routers.kvikshaug-static.entryPoints=websecure"
      - "traefik.http.routers.kvikshaug-static.tls=true"
      - "traefik.http.routers.kvikshaug-static.tls.certresolver=letsencrypt"

  web:
    build: .
    image: kvikshaug.no
    volumes:
      - "./logs:/app/logs"
    environment:
      - ENVIRONMENT=production
      - FLASK_SKIP_DOTENV=1
      - SECRET_KEY=${SECRET_KEY}
    command: gunicorn -c gunicorn.py kvikshaug.wsgi:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.kvikshaug.loadBalancer.server.port=8000"
      - "traefik.http.routers.kvikshaug.rule=Host(`kvikshaug.no`)"
      - "traefik.http.routers.kvikshaug.entryPoints=websecure"
      - "traefik.http.routers.kvikshaug.tls=true"
      - "traefik.http.routers.kvikshaug.tls.certresolver=letsencrypt"

  sass:
    image: kvikshaug.no
    volumes:
      - ".:/app"
    command: sass -s compressed assets/sass:assets/css

  babel:
    image: kvikshaug.no
    volumes:
      - ".:/app"
    command: babel --verbose js -d assets/js
