services:
  web:
    build: .
    image: kvikshaug.no
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - kvikshaug
    volumes:
      - ".:/app"
    environment:
      - ENVIRONMENT=development
      - FLASK_SKIP_DOTENV=1
    command: gunicorn -c gunicorn.py kvikshaug.wsgi:app

  sass:
    image: kvikshaug.no
    volumes:
      - ".:/app"
    command: sass --watch -s compressed assets/sass:assets/css
    stop_signal: SIGKILL

  babel:
    image: kvikshaug.no
    volumes:
      - ".:/app"
    command: babel --verbose --watch js -d assets/js
    stop_signal: SIGKILL
